### ISSUE TITLE
libvl.so: cannot open shared object file

### ISSUE THREAD

**Issue by NathanCrombez** [doda42/LiFF#1]
Hi,

I'm working on Ubuntu 16.04, MATLAB 2016b. I have downloaded the sources and I have rebuild the mex binary files from source using the make_linux.m script (gcc 4.9). The MEX build is completed successfully. However, when I try to extract features on a LF using "LiFF_ExtractFeatures(LF)", I got : 

Invalid MEX-file '[...]/LiFF_ExtractFeatures.mexa64': libvl.so: cannot open shared object file No such file or directory

Any idea ?

**Comment by doda42** [comment]
Good point. On Linux systems you need to tell linux where to find libvl.so. One way to do this is to add the following to .bashrc, changing <path to LiFF> appropriately:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/<path to LiFF>/lib/vlfeat-0.9.21/toolbox/mex/mexa64/
Be sure to re-launch matlab from a fresh bash shell to make sure the .bashrc changes take effect.  The same issue comes up for vl_feat users, and a few alternative solutions exist (search vlfeat libvl.

**Comment by NathanCrombez** [comment]
Thank you very much! It works.
An example on a Lytro V1 LF (uncalibrated) :
![liff_prem](https://user-images.githubusercontent.com/25529025/51179770-cf2dfe80-18c6-11e9-8d5b-d3e2f053d1cc.png)
